---

# tasks/configuration.yml

- name: replace local address in postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/11/data/postgresql.conf
    regex: '^listen_addresses'
    insertbefore: '^#listen_addresses'
    line: "listen_addresses = '*'"

- name: Adding hosts
  lineinfile:
    path: /var/lib/pgsql/11/data/pg_hba.conf
    regex: '^IPv4'
    insertafter: '^# IPv4 local connections:'
    line: "host     all         all      0.0.0.0/0   ident"    
